In [52]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
dataset = pd.read_csv('machineLearningBasic/datasets/Social_Network_Ads.csv')

In [4]:
#X = dataset[['Age', 'EstimatedSalary']].values.astype("float32")
# 연령과 연봉을 줄테니 구매를 할지 말지 알아맞춰보기
X = dataset.iloc[:, [2,3]].values.astype("float32")
y = dataset.iloc[:, 4].values.astype("float32")

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train) #training 과 Standard Scaling 형태로 변환
X_test_scaled = sc.transform(X_test) # fit 하지 말고 형태 변환만 시켜주기

In [7]:
clf = SVC(kernel='rbf')

In [8]:
clf.fit(X_train_scaled, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [10]:
y_pred = clf.predict(X_test_scaled)

In [11]:
y_pred

array([1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [15]:
print(confusion_matrix(y_test, y_pred, labels=[1,0]))

[[25  3]
 [ 5 47]]


In [16]:
cell_df = pd.read_csv("machineLearningBasic/datasets/cell_samples.csv")

In [17]:
cell_df.dtypes

ID              int64
Clump           int64
UnifSize        int64
UnifShape       int64
MargAdh         int64
SingEpiSize     int64
BareNuc        object
BlandChrom      int64
NormNucl        int64
Mit             int64
Class           int64
dtype: object

In [18]:
feature_df = cell_df.drop(['ID', 'BareNuc'], axis=1)

In [34]:
feature_df.head(10)

Clump  UnifSize  UnifShape  MargAdh  SingEpiSize  BlandChrom  NormNucl  \
0      5         1          1        1            2           3         1   
1      5         4          4        5            7           3         2   
2      3         1          1        1            2           3         1   
3      6         8          8        1            3           3         7   
4      4         1          1        3            2           3         1   
5      8        10         10        8            7           9         7   
6      1         1          1        1            2           3         1   
7      2         1          2        1            2           3         1   
8      2         1          1        1            2           1         1   
9      4         2          1        1            2           2         1   

   Mit  Class  
0    1      2  
1    1      2  
2    1      2  
3    1      2  
4    1      2  
5    1      4  
6    1      2  
7    1      2  
8    5      2  
9    1      2

In [36]:
# dataframe 을 numpy array 로 변환

X = feature_df.iloc[:, :-1].values.astype("float32")
y = feature_df.iloc[:, -1].values.astype("float32")

In [35]:
# Train/Test dataset 분리

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [44]:
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [46]:
X_train_scaled

array([[-0.1598217 , -0.7101785 , -0.7480339 , ..., -0.610779  ,
        -0.6292659 , -0.3543089 ],
       [ 0.19611588,  1.2534971 ,  0.24441297, ...,  1.4166881 ,
         2.2858694 ,  0.8005522 ],
       [ 1.9758039 ,  1.5807765 ,  1.5676755 , ...,  1.8221813 ,
         1.3141576 ,  3.687705  ],
       ...,
       [-0.5157593 ,  0.27165937,  0.57522863, ...,  0.20020784,
        -0.6292659 , -0.3543089 ],
       [-1.2276344 , -0.7101785 , -0.7480339 , ..., -0.610779  ,
        -0.6292659 , -0.3543089 ],
       [ 1.6198663 ,  1.2534971 ,  1.2368599 , ...,  1.4166881 ,
         1.6380615 ,  0.8005522 ]], dtype=float32)

In [ ]:
clf = SVC(kernel='rbf')
clf.fit(X_train_scaled, y_train)

y_pred = clf.predict(X_test_scaled)

In [53]:
print("confution matrix\n", confusion_matrix(y_test, y_pred, labels=[4, 2]))
print()
print("classification report\n", classification_report(y_test, y_pred, labels=[4, 2]))

confution matrix
 [[41  1]
 [ 4 94]]

classification report
               precision    recall  f1-score   support

           4       0.91      0.98      0.94        42
           2       0.99      0.96      0.97        98

   micro avg       0.96      0.96      0.96       140
   macro avg       0.95      0.97      0.96       140
weighted avg       0.97      0.96      0.96       140

