In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [5]:
dataset = pd.read_csv('machineLearningBasic/datasets/Social_Network_Ads.csv')

In [8]:
dataset.tail(7)

User ID  Gender  Age  EstimatedSalary  Purchased
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [9]:
dataset['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [20]:
#X = dataset[['Age', 'EstimatedSalary']].values.astype("float32")
# 연령과 연봉을 줄테니 구매를 할지 말지 알아맞춰보기
X = dataset.iloc[:, [2,3]].values.astype("float32")
y = dataset.iloc[:, 4].values.astype("float32")
y

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 1., 1., 0., 0.

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [25]:
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train) #training 과 Standard Scaling 형태로 변환
X_test_scaled = sc.transform(X_test) # fit 하지 말고 형태 변환만 시켜주기

In [46]:
X_train_scaled.shape

(320, 2)

In [23]:
X_train[:5]

array([[2.00e+01, 3.60e+04],
       [3.90e+01, 9.60e+04],
       [5.30e+01, 1.04e+05],
       [3.80e+01, 6.50e+04],
       [3.10e+01, 6.80e+04]], dtype=float32)

In [26]:
X_test_scaled[:5]

array([[-1.6997162 ,  0.38932678],
       [-1.1259724 ,  0.35990894],
       [ 0.7865073 , -1.1992368 ],
       [ 0.8821313 , -0.5520442 ],
       [-0.36098054,  0.09514834]], dtype=float32)

In [29]:
lr_clf = LogisticRegression(solver='lbfgs')
# LogisticRegression PARAMETER 중요한 거 알려주심.
# solver -> 옵티마이저. 손실함수를 최소화하는 프로그램.

In [47]:
lr_clf.fit(X_train_scaled, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [48]:
y_pred = lr_clf.predict(X_test_scaled)

In [55]:
print("{}".format(sum(y_test)))
print("{}".format(sum(y_pred)))

29.0
21.0


In [49]:
y_pred # 예측값이 나옴. 0.5를 기준으로 높으면 1, 낮으면 0 (0,1)

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.], dtype=float32)

In [35]:
y_pred_proba = lr_clf.predict_proba(X_test_scaled)

In [39]:
 # 확률이 나옴. 위의 함수보다 좀더 엄격하게. 0.5 기준이 아니라 내가 조정할 수 있음
y_pred_proba > 0.5
y_pred_proba

In [50]:
from sklearn.metrics import confusion_matrix

In [51]:
print(confusion_matrix(y_test, y_pred, labels=[1,0]))

[[18 11]
 [ 3 48]]


In [60]:
conf_mat = confusion_matrix(y_test, y_pred, labels=[1,0])
conf_mat.shape

(2, 2)